# Generated by Django 3.2.4 on 2021-06-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youngs_modulus', models.DecimalField(decimal_places=4, max_digits=10)),
                ('compressive_strength', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeismicQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shear_deformation', models.DecimalField(decimal_places=4, max_digits=10)),
                ('soil_shear_modulus', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('density', models.DecimalField(decimal_places=4, max_digits=10)),
                ('SLS_bearing_strength', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ULS_bearing_strength', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hydraulic_conductivity_horizontal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hydraulic_conductivity_vertical', models.DecimalField(decimal_places=3, max_digits=10)),
                ('earth_pressure_at_rest', models.DecimalField(decimal_places=3, max_digits=10)),
                ('layer_thinckness', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TunnelFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roof_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inverse_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_inner_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_outer_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_inner_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_outer_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haunch_depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haunch_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cracking_mod_compressive', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cracking_mod_shear', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cracking_mod_bending', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_description', models.CharField(max_length=250)),
            ],
        ),
    ]
