# Generated by Django 3.2.4 on 2021-07-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youngs_modulus', models.DecimalField(decimal_places=4, max_digits=10)),
                ('compressive_strength', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeismicQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shear_deformation', models.DecimalField(decimal_places=4, max_digits=10)),
                ('soil_shear_modulus', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoilLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('density', models.DecimalField(decimal_places=4, max_digits=10)),
                ('SLS_bearing_strength', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ULS_bearing_strength', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hydraulic_conductivity_horizontal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hydraulic_conductivity_vertical', models.DecimalField(decimal_places=3, max_digits=10)),
                ('earth_pressure_at_rest', models.DecimalField(decimal_places=3, max_digits=10)),
                ('layer_thinckness', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TunnelFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_system', models.CharField(choices=[('Metric_Standard', 'KN mm C')], default='Metric_Standard', max_length=15)),
                ('plane', models.CharField(choices=[('xy', 'x-y'), ('xz', 'x-z'), ('yz', 'y-z')], default='xz', max_length=2)),
                ('roof_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('inverse_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wall_slab_thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_inner_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_outer_height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_inner_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('frame_outer_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haunch_depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('haunch_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cracking_mod_compressive', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('cracking_mod_shear', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('cracking_mod_bending', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('frame_description', models.CharField(max_length=250)),
                ('concourse_slab_thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('concourse_haunch_depth', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('concourse_haunch_width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('concrete_strength', models.CharField(default='4000Psi', max_length=12)),
                ('column_bays', models.IntegerField(default=1)),
                ('column_capital_height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('column_capital_width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('concourse_slab_vertical_location', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('column_width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoadDefinition',
            fields=[
                ('parent_frame_description', models.CharField(max_length=100, null=True)),
                ('load_id', models.AutoField(primary_key=True, serialize=False)),
                ('load_pattern_description', models.CharField(choices=[('LL', 'Live Load'), ('SL', 'Soil Load')], max_length=20)),
                ('load_direction', models.CharField(choices=[('G', 'Gravity'), ('H', 'Horizontal')], max_length=20)),
                ('start_force', models.FloatField()),
                ('end_force', models.FloatField()),
                ('load_location', models.CharField(choices=[('RS', 'Roof Slab'), ('FS', 'Floor Slab'), ('CS', 'Concourse Slab')], max_length=2)),
                ('parent_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunnel_app.tunnelframe')),
            ],
        ),
        migrations.CreateModel(
            name='FrameMember',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_ordinate_system', models.CharField(choices=[('GLOBAL', 'GLOBAL')], default=('GLOBAL', 'GLOBAL'), max_length=20)),
                ('line_object_type', models.CharField(choices=[('str_fr', 'Straight Frame')], max_length=20)),
                ('start_joint', models.IntegerField()),
                ('end_joint', models.IntegerField()),
                ('parent_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunnel_app.tunnelframe')),
            ],
        ),
        migrations.CreateModel(
            name='FrameJoint',
            fields=[
                ('joint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('x_coordinate', models.FloatField(max_length=5)),
                ('y_coordinate', models.FloatField(max_length=5)),
                ('z_coordinate', models.FloatField(max_length=5)),
                ('parent_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunnel_app.tunnelframe')),
            ],
        ),
    ]
