# Generated by Django 3.2.4 on 2021-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_bending',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_compressive',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_shear',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
