# Generated by Django 3.2.4 on 2021-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0002_tunnelframe_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='column_capital_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='column_capital_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='column_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concourse_haunch_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concourse_haunch_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concourse_slab_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concourse_slab_vertical_location',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_bending',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_compressive',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='cracking_mod_shear',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='frame_inner_height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='frame_inner_width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='frame_outer_height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='frame_outer_width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='haunch_depth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='haunch_width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='inverse_slab_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='roof_slab_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='wall_slab_thickness',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
