# Generated by Django 3.2.4 on 2021-08-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0003_auto_20210728_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddefinition',
            name='load_direction',
            field=models.CharField(choices=[('Gravity', 'Gravity'), ('Horizontal', 'X')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='load_location',
            field=models.CharField(choices=[('RS', 'Roof Slab'), ('FS', 'Floor Slab'), ('CS', 'Concourse Slab'), ('LW', 'Left Wall'), ('RW', 'Right Wall')], max_length=2),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='load_pattern_description',
            field=models.CharField(choices=[('LL_RS', 'Live Load'), ('LL_CS', 'Live Load'), ('H_L', 'Horizontal Load Left'), ('R_L', 'Horizontal Load Right')], max_length=20),
        ),
    ]
