# Generated by Django 3.2.4 on 2021-08-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0004_auto_20210803_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaddefinition',
            name='force_end_depth',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='loaddefinition',
            name='force_start_depth',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='load_direction',
            field=models.CharField(choices=[('Gravity', 'Gravity'), ('X', 'Horizontal (X-Plane)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='load_pattern_description',
            field=models.CharField(choices=[('LL_RS', 'Live Load Roof Slab'), ('LL_CS', 'Live Load Concourse Slab'), ('H_L', 'Soil Load Left Side Frame'), ('R_L', 'Soil Load Right Side Frame')], max_length=20),
        ),
    ]
