# Generated by Django 3.2.4 on 2021-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0006_auto_20210805_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='column_capital_roof_slab_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='column_capital_roof_slab_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
