# Generated by Django 3.2.4 on 2021-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0008_auto_20210806_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddefinition',
            name='force_end_depth',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='force_start_depth',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
