# Generated by Django 3.2.4 on 2021-08-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0009_auto_20210806_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='column_stiffness_modifiers',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='slab_stiffness_modifiers',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='wall_stiffness_modifiers',
            field=models.FloatField(null=True),
        ),
    ]
