# Generated by Django 3.2.4 on 2021-08-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0010_auto_20210807_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tunnelframe',
            old_name='column_stiffness_modifiers',
            new_name='column_stiffness_modifier',
        ),
        migrations.RenameField(
            model_name='tunnelframe',
            old_name='slab_stiffness_modifiers',
            new_name='slab_stiffness_modifier',
        ),
        migrations.RenameField(
            model_name='tunnelframe',
            old_name='wall_stiffness_modifiers',
            new_name='wall_stiffness_modifier',
        ),
    ]
