# Generated by Django 3.2.4 on 2021-08-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0011_auto_20210807_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaddefinition',
            name='force_end_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loaddefinition',
            name='force_start_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
