# Generated by Django 3.2.4 on 2021-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0012_auto_20210807_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='concrete_strength_columns',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='concrete_strength_slabs',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='concrete_strength_walls',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='column_stiffness_modifier',
            field=models.FloatField(default=0.7, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='slab_stiffness_modifier',
            field=models.FloatField(default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='wall_stiffness_modifier',
            field=models.FloatField(default=0.7, null=True),
        ),
    ]
