# Generated by Django 3.2.4 on 2021-08-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0013_auto_20210808_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='concrete_strength_columns',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concrete_strength_slabs',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='concrete_strength_walls',
            field=models.IntegerField(default=5000),
        ),
    ]
