# Generated by Django 3.2.4 on 2021-08-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0015_tunnelframe_column_depth_for_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='dimension_system',
            field=models.CharField(choices=[('Metric_Standard', 'N mm C')], default='Metric_Standard', max_length=15),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='plane',
            field=models.CharField(choices=[('xz', 'x-z')], default='xz', max_length=2),
        ),
    ]
