# Generated by Django 3.2.4 on 2021-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0016_auto_20210818_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='frame_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
