# Generated by Django 3.2.4 on 2021-08-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0017_tunnelframe_frame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='haunch_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='haunch_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
