# Generated by Django 3.2.4 on 2021-08-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0018_auto_20210826_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='base_restraint',
            field=models.BooleanField(default=False),
        ),
    ]
