# Generated by Django 3.2.4 on 2021-09-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0019_tunnelframe_base_restraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelframe',
            name='inverse_slab_stiffness',
            field=models.IntegerField(default=55000),
        ),
        migrations.AddField(
            model_name='tunnelframe',
            name='wall_slab_stiffness',
            field=models.IntegerField(default=20000),
        ),
    ]
