# Generated by Django 3.2.4 on 2021-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel_app', '0020_auto_20210901_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnelframe',
            name='inverse_slab_stiffness',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='tunnelframe',
            name='wall_slab_stiffness',
            field=models.IntegerField(default=20),
        ),
    ]
